-- To use this file, navigate to the "SQL Editor" in your Supabase project dashboard,
-- paste the content of this file, and click "Run".

CREATE TABLE public.users (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  spotify_id text NOT NULL,
  email text NOT NULL,
  username text NULL,
  points integer NOT NULL DEFAULT 1000,
  referral_code text NULL,
  referred_by bigint NULL,
  premium_status boolean NOT NULL DEFAULT false,
  last_claimed_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_email_key UNIQUE (email),
  CONSTRAINT users_referral_code_key UNIQUE (referral_code),
  CONSTRAINT users_spotify_id_key UNIQUE (spotify_id),
  CONSTRAINT users_referred_by_fkey FOREIGN KEY (referred_by) REFERENCES public.users(id)
);

-- Note: The default points are set to 1000 as per the requirements.
-- Premium users will get an additional 500 points, which will be handled in the application logic.
